### ISSUE TITLE
Investigate Hot Restart not working on Android in a customer project

### ISSUE THREAD

**Issue by jBorkowska** [leancodepl/patrol#1066]
More info: contact @zoskar

**Comment by bartekpacia** [comment]
I checked that project and it looks like `patrol: 1.0.4` was used (while [Hot Restart is supported since `patrol: 1.0.6`](https://pub.dev/packages/patrol/changelog#106)). After updating, Hot Restart works just fine.

Please, always make sure you're using the latest versions before raising a bug. @zoskar
