### ISSUE TITLE
Support for BDD

### ISSUE THREAD

**Issue by MitkoTschimev** [leancodepl/patrol#1160]
Thank you very much for this great support for better integration tests!

We appreciate your work and how it fixes many issues the flutter team still needs to tackle.
Our product/team uses BDD for testing because it fits our philosophy of testing in the best way.

Do you have any plans to include this testing strategy and make it compatible with patrol?

**Comment by bartekpacia** [comment]
Hi @MitkoTschimev, thanks for the kind words :) We're happy that you find Patrol useful.

We don't have plans to add any kind of BDD support to Patrol itself, but we'd be happy to see the community build BDD-related tooling around it. In fact, some time ago, @nonvachara-paloit managed to get [flutter_gherkin](https://pub.dev/packages/flutter_gherkin) (one of the most popular BDD packages for Flutter, I think) to work with Patrol. See [this discussion](https://github.com/leancodepl/patrol/discussions/652) to learn more. 

I haven't tested it, and because of breaking changes in Patrol, some of the code in that discussion may require a bit of refactoring, but in principle, it works.

**Comment by bartekpacia** [comment]
Closing since there's no work to be done on our side.
