### ISSUE TITLE
Patrol test never finishes when more than one group is included in a file

### ISSUE THREAD

**Issue by mateuszwojtczak** [leancodepl/patrol#1235]

**Comment by bartekpacia** [comment]
I understand that this is concerning the issue that @jBorkowska encountered when testing the `customer: rower`'s app.

We resolved it. If it's not that, feel free to reopen.


BTW, `group()`s currently work just fine with Patrol, but will stop once we release test bundling. That's because our logic depends on the name of the `test()`'s immediate parent group to be the Dart test file name (and that group is generated by Patrol CLI in `bundled_test.dart`).
