### ISSUE TITLE
Support running on multiple devices simultaneously

### ISSUE THREAD

**Issue by mateuszwojtczak** [leancodepl/patrol#15]

**Comment by bartekpacia** [comment]
The very basic version was done in #253. The logging output is a mess though because logs from all devices on which tests are being run are cluttered together. And probably more problems exist that we're not aware of yet - this feature (of running on many devices simultaneously) was barely tested. 

That said, I'm pretty sure that this issue can be closed. We've proved that it is possible. Let's open a new issue if we want to continue working on this feature.
