### ISSUE TITLE
Stop depending on gRPC on iOS 

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#1532]
Because it's way too heavy & increases build times by a lot. (We could profile and get more data, but I'm sure it'll only confirm this thesis).

Alternative: define and handle commands & queries manually. Use something like [swhitty/FlyingFox](https://github.com/swhitty/FlyingFox) or [Building42/Telegraph](https://github.com/Building42/Telegraph) as HTTP server.

**Comment by bartekpacia** [comment]
Some context:
We migrated to gRPC in #338. We weren't aware of how heavy this library is on iOS.

This issue essentially proposes reverting that change on iOS. Android is out of scope of this, but worth discussing as well. Having one platform use gRPC, and the other not, sounds bad.

**Comment by bartekpacia** [comment]
If we stop depending on gRPC on iOS, it'll make little sense to also use it for Android and Dart side. So we'll essentially have to get rid of gRPC altogether.

Idea: could we use `package:pigeon` for this? It seems like a more lightweight codegen solution. Can pigeon messages be sent across processes, not only through Flutter's platform channels?

**Comment by shilangyu** [comment]
> Idea: could we use `package:pigeon` instead of gRPC? It seems like a more lightweight codegen solution. Can pigeon messages be sent with e.g. HTTP, not only through Flutter's platform channels? In other words, can we do `toJson`/`fromJson` on pigeon-generated messages?

Not really. It is quite channels specific. 

I am not a fan of it, but what about just using OpenAPI? It's the most lightweight. All platforms have support for it. Swift and Kotlin have server generators for it too.

**Comment by bartekpacia** [comment]
We were thinking about it (@zltnDC even tried it out), but OpenAPI generators for Dart are mediocre and poorly maintained.

**Comment by shilangyu** [comment]
> OpenAPI generators for Dart are mediocre and poorly maintained.

Were there any specific problems? I would have guess you need quite basic functionality for patrol. We use these generators in a few projects without any bigger issues.

**Comment by zltnDC** [comment]
If I remember correctly I tried using a custom configuration but the output didn't compile, some helpers method were missing and there were import problems. Swift also had small inconvenient issue. So, we thought about what we needed and decided to write a custom generation. Some of these points are:
- if possible, reduce additional dependencies/technologies
- models - easy to generate because we need a small subset
- server/client (swift, dart, kotlin) - we can easy implement or change internal implementation: "URLSeession", "dio", "http", "FlyingFox" etc. Swagger generators offer a smaller subset or don't provide the ability to generate routes or any convinient class to hide communications etc. "lightweight" servers "Telegraph", "FlyingFox" are good examples. 
- we can easily maintain consistency across all platforms
- We needed a simple way to add additional methods to contracts if necessary. Grpc uses pattern: property, hasProperty. We use this on the kotlin side and we are considering keeping this pattern for dart contracts (Patrol exports NativeView, Notification, Selector)
- I also see some patterns, such as:  _wrapRequest('Name', ()=>...), _runCatching {} etc. We can easily move these things to the generated code and developers won't think about it.

And a few other issues that me and Bartek forgot.

**Comment by jBorkowska** [comment]
Closing, if there is something else to do regarding this task please create a new one
