### ISSUE TITLE
Find out what method of screenshot taking is the best

### ISSUE THREAD

**Issue by mateuszwojtczak** [leancodepl/patrol#24]
Can we use `flutter screenshot` or maybe we'll have to use the screenshot server like Appium does

**Comment by edgarfroes** [comment]
To add some context to this issue, it's only possible to take screenshots on Flutter's native API by using `flutter driver` instead of `flutter test`, as per this article.

Also, since Patrol uses XCTest, taking screenshots might not be possible on iOS because of [this issue](https://github.com/flutter/flutter/issues/91668), so, for iOS, this feature might require further investigation.

Useful issues:
[Generate screenshot using flutter test integration_test command](https://github.com/flutter/flutter/issues/101476#top)
[Take screenshot during Flutter integration tests](https://dev.to/mjablecnik/take-screenshot-during-flutter-integration-tests-435k)

**Comment by bartekpacia** [comment]
Closing, let's open a new issue instead of reviving this one.
