### ISSUE TITLE
Research debugging of tests & compatibility with IDEs

### ISSUE THREAD

**Issue by mateuszwojtczak** [leancodepl/patrol#323]

**Comment by bartekpacia** [comment]
Check if/how convenient_test does debugging.

**Comment by bartekpacia** [comment]
See also:
- https://github.com/Dart-Code/Dart-Code/issues/4206, which blocks us
- #404, which shows what's currently possible

**Comment by JulianBissekkou** [comment]
I was looking for a way to debug a patrol test inside my IDE and came across this issue.
#404 mentions the use of `flutter attach` but I don't see any documentation on how I can start/debug a test from my IDE.

Maybe we can describe this here because someone might also search for "IDE" or "debug" in the issue list.
