### ISSUE TITLE
How to find widget by itself using (like `find.byWidget()` does)

### ISSUE THREAD

**Issue by burhankhanzada** [leancodepl/patrol#401]
Let's just say I have multiple widgets of the same type in a list and first i have used find by type then I want to tap on the first item then I used find widget by widget how can we do this in patrol

```dart
void main() {
  testWidgets('some test'), () async {
    await app.main();
    await tester.pumpAndSettle();

    final cards = find.byType(Card);

    expect(cards, findsNWidgets(4));

    final firstCard = cards.evaluate().first.widget;

    final card = find.byWidget(firstCard);

    await tester.ensureVisible(card);
    await tester.pumpAndSettle();
    await tester.tap(card);
  }
}
```

**Comment by bartekpacia** [comment]
Hi @burhankhanzada!

If I understand you correctly, then you'd want something like this:

```dart
patrolTest('patrol', (PatrolTester $) async {
    await $.pumpWidgetAndSettle(const MyApp());

    final cardFinder = $(Card);
    expect(cardFinder, findsNWidgets(4));

    final firstCard = cardFinder.evaluate().first.widget;

    final card = $(firstCard);

    await card.waitUntilVisible();

    await card.tap();
  });
```

Unfortunately, this is not currently possible, because `$` doesn't accept `Widget`. This is a good feature request though, and [I've already submitted a PR](https://github.com/leancodepl/patrol/pull/402) for this. Should be merged very soon :) 

Thanks for creating the issue! 💙 We hope you like Patrol. If you have any further questions, don't hesitate!

**Comment by bartekpacia** [comment]
In `patrol v0.6.10`, this is now valid:

```dart
patrolTest('patrol', (PatrolTester $) async {
    await $.pumpWidgetAndSettle(const MyApp());

    final cardFinder = $(Card);
    expect(cardFinder, findsNWidgets(4));

    final firstCard = cardFinder.evaluate().first.widget;

    final card = $(firstCard);

    await card.waitUntilVisible();

    await card.tap();
  });
```

**Comment by burhankhanzada** [comment]
yeah thats exactly what i want, Also thank you very much for this quick fix & release
