### ISSUE TITLE
Unable to click Android Native Location pop-up in Redmi Note 9 device

### ISSUE THREAD

**Issue by shridharkalagi** [leancodepl/patrol#407]
`    await $.native.grantPermissionOnlyThisTime();` This doesn't seem to work on Redmi Note 9 device with Android 11 OS. The logs say 
`Patrol: grantPermissionOnlyThisTime() started
Patrol: grantPermissionOnlyThisTime() succeeded` . However, the pop-up still remains and the test case fails. Can you please help?

**Comment by bartekpacia** [comment]
Hi @shridharkalagi, thanks for using Patrol! I'm sorry that you encountered this problem.

First, the logs say the action was successful because if Patrol can't find the dialog, it will just assume that _it's fine_ and not raise an error. I think this behavior is misleading and we'll change it.

Now, I think that the problem lies in the device you're using; namely, the MIUI flavor of Android. I'm pretty sure that it differs from the "clean" Android that we've been testing Patrol on. This is definitely a bug and we'll want to fix it.

I'm going to ask you to do the following:

1. Open your app normally (through VS Code, or just `flutter run`).
2. Reach the location in your app when the permission dialog is shown. Don't click on it.
3. Run the following:

   ```
   $ adb shell uiautomator dump && adb pull /sdcard/window_dump.xml .
   ```

4. Paste the `window_dump.xml` file. You can create a gist and send a link to the gist here.

When I will know the view hierarchy when the dialog is shown, I'll be able to make appropriate fixes to Patrol so that it will be aware of MIUI differences.

**Comment by shridharkalagi** [comment]
@bartekpacia can you please suggest any workaround for the time being?

**Comment by bartekpacia** [comment]
You can try tapping on the dialog's button manually:

```dart
await $.native.tap(Selector(text: 'Only this time'));
```

**Comment by bartekpacia** [comment]
Please share video recording of the test and the logs (run Patrol CLI with `--verbose`).

**Comment by bartekpacia** [comment]
BTW I see your dialog's button has text `"ONLY THIS TIME"`, not `"Only this time"`. Try if fixing the casing works.

**Comment by bartekpacia** [comment]
@shridharkalagi I'm going to close this issue because of the lack of response. Feel free to comment any time with more data that I requested above (video recording (if possible) and logs). Also, do update Patrol to the newest version – we're constantly working on improving the stability.
