### ISSUE TITLE
Webview interaction - selecting correct element when Selector applies to multiple elements

### ISSUE THREAD

**Issue by PiotrMitkowski** [leancodepl/patrol#663]
Let's assume the following login form:
<img width="443" alt="Zrzut ekranu 2022-12-5 o 13 02 44" src="https://user-images.githubusercontent.com/1737922/205632999-1feabd43-d24d-4540-9038-06ea8dc117d6.png">

My app opens it in a web view, and I want to put some login and password and tap the "Log in" button. I use the following code:

```dart
await $.native.enterTextByIndex('some_login', index: 0);
await $.native.enterTextByIndex('some_password', index: 1);
await $.native.tap(Selector(text: 'Log in'));
```

Entering the text works like a charm, but the `tap()` command selects the header above the fields instead of the button. I tried with `className: 'button'`, `'className: 'Button'` (inspired by the [article on Medium](https://medium.com/azimolabs/android-webview-automation-testing-6311df8fe42e)), but it couldn't find such element. I also tried playing with the `instance` field, but I only got `IllegalArgumentException` with a message saying, that `instance` isn't supported.

Is there a way to select the button in such case?

**Comment by bartekpacia** [comment]
Hi again :)

You've hit quite an ugly corner case, which I also don't like. But before I start complaining on Android's [crippled](https://developer.android.com/reference/androidx/test/uiautomator/BySelector) [UI](https://developer.android.com/reference/androidx/test/uiautomator/UiSelector) [selectors](https://developer.android.com/reference/androidx/test/uiautomator/UiObject2) [in tests](https://developer.android.com/reference/androidx/test/uiautomator/UiObject), please try with `className: android.widget.Button` instead of `className: `button`. It would also help if you did a [native view hierarchy dump](https://patrol.leancode.co/tips-and-tricks#inspecting-native-view-hierarchy) and shared it here (or at least part of it, if you're under some NDA)

**Comment by PiotrMitkowski** [comment]
`'android.widget.Button'` worked like a charm, thanks! Do you still want to see the native view hierarchy?

**Comment by bartekpacia** [comment]
I'm happy that you solved it :)

But if you had two `Button` widgets with text "Log in", then this wouldn't be possible to do in Patrol. I'll keep this issue open until I find a nice fix.

**Comment by bartekpacia** [comment]
@PiotrMitkowski I implemented this feature in #849 :) 

https://user-images.githubusercontent.com/40357511/215361937-b56aae88-2b59-44e7-82a2-adaea09533b4.mov

**Comment by bartekpacia** [comment]
Android is done, iOS todo.

**Comment by bartekpacia** [comment]
#952 was reverted in #1042
