### ISSUE TITLE
Kill/close currently running app

### ISSUE THREAD

**Issue by mzdm** [leancodepl/patrol#722]
Is it possible to kill/close the currently running app? A typical use case would be to test the login case: `login screen -> login -> kill app -> open app again` and the user should stay logged in and be on the home page.

**Comment by bartekpacia** [comment]
Hi, this is not possible, because in Flutter, your test runs _inside_ the app. Therefore, if you killed your app, you'd also kill your test.

After a `*_test.dart` finishes running, the app is uninstalled, and the next `*_test.dart` file will run as a freshly installed application.

I recommend extracting common login logic into a function, and calling that function from other test files.

Let me know if you have any more questions and I'll be happy to answer.

I'm going to mark this PR as closed because this use case is not supported currently by Flutter. [There's an issue tracking this feature](https://github.com/flutter/flutter/issues/48955), though.
