### ISSUE TITLE
hostAutomator not found

### ISSUE THREAD

**Issue by Gaurav-CareMonitor** [leancodepl/patrol#887]
The getter 'hostAutomator' isn't defined for the type 'PatrolTester'.
Try importing the library that defines 'hostAutomator', correcting the name to the name of an existing getter, or defining a getter or field named 'hostAutomator'
<img width="670" alt="image" src="https://user-images.githubusercontent.com/113885801/216887893-5ffbc2ec-7f8f-4e8f-ab34-22781aba4f92.png">

**Comment by Gaurav-CareMonitor** [comment]
patrol v ^0.10.9

**Comment by bartekpacia** [comment]
Hi @Gaurav-CareMonitor, sorry, but this has been removed. We've never mentioned it in the docs because we considered it an experimental feature, and it was scheduled for removal in 1.0.

To still use this feature (which I don't recommend), you'll have to rollback to an older `patrol_cli`:
- Clone the repo
- `cd packages/patrol_cli`
- `git checkout patrol_cli-v0.8.2`
- build the executable: `dart pub global activate --source path . && patrol`

We do want to bring these features back - see #788.

**Comment by Gaurav-CareMonitor** [comment]
@bartekpacia is there any way to capture screenshots then?

**Comment by bartekpacia** [comment]
Currently - no.

As a workaround, you can use `adb shell screenrecord` (to record a video).
