### ISSUE TITLE
iOS integration test displays test class name in red label

### ISSUE THREAD

**Issue by sebroehl** [leancodepl/patrol#909]
Hey everyone,

I'm trying to do some automatic screenshot generation and I'm executing my test with `patrol drive` for that. 
The problem is that the simulator displays the name of the test class in a red label across the screens (screenshot attached).

<img width="703" alt="image" src="https://user-images.githubusercontent.com/26088587/217834946-74dfd867-3180-403a-9bf8-f58516ad8a09.png">

Is there any way to get rid of this?

Thanks a lot and all the best
Sebastian

**Comment by bartekpacia** [comment]
Hi :)

If you're using `patrol drive`, you can pass `--no-label` to prevent this behavior.

PS `patrol drive` is deprecated and we're going to remove it very soon – [migrate to patrol test](https://patrol.leancode.co/native/setup). Sorry about the inconvenience but we had to fundamentally change our architecture in order to solve some important issues.
