### ISSUE TITLE
Notch on device causes fails on some occasions

### ISSUE THREAD

**Issue by zoskar** [leancodepl/patrol#944]
**Describe the bug**

Patrol tests sometimes have trouble with `scrollTo().tap()` behavior while running it on emulators with notch. It tends to scroll the widget and place it behind the notch which blocks patrol from tapping on it.

**Device information**

- Device: iPhone 14 Pro Max emulator
- Does it also both on physical and virtual devices? Didn't check

  

<details>
<summary>Additional information</summary>

`% flutter --version
Flutter 3.3.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision eb6d86ee27 (4 months ago) • 2022-10-04 22:31:45 -0700
Engine • revision c08d7d5efc
Tools • Dart 2.18.2 • DevTools 2.15.0`

`  patrol: ^1.0.0
`

`patrol --version
patrol_cli v1.0.0
`
</details>

**Comment by jBorkowska** [comment]
We spotted it in another place: there is scrollable covering whole bottom sheet (or something similar) and a widget on the top of the screen, which "floats" (kind of overlay). When we scroll, we scroll until the found widget is scrolled to maximum, but then it is hidden behind the overlay, which makes it not hittestable.

Potential fix: instead of scrolling to the max top of scrollable, scroll only to half of its height (it's more user-like behavior).

**Comment by jBorkowska** [comment]
To check after scrolling rework

**Comment by zoskar** [comment]
@jBorkowska For scenarios with scrolling down no problem can ever occur since after scroll rework Patrol does not scroll widget to the top of the screen. As for scrolling up I checked it with `step: 20` in `scrollTo()` with iPhone 14 Pro Max (huge notch) and Patrol scrolled until given item was below notch.
