### ISSUE TITLE
Can `PatrolFinder.which()` be written shorter (without type argument)?

### ISSUE THREAD

**Issue by matiasleyba** [leancodepl/patrol#946]
Hello! 👋🏻
I'm using the `which` method and I wonder if there is a way to make it shorter with Patrol, is it possible?

Example:
![image](https://user-images.githubusercontent.com/18689004/219394053-5a0111cf-4844-4507-a031-118749a3ff64.png)

I started using the library and it's awesome! Thanks for your great work on it. 🚀

**Comment by bartekpacia** [comment]
Hi @matiasleyba :) Thanks for the kind words.

[PatrolFinder.which() method](https://pub.dev/documentation/patrol/latest/patrol/PatrolFinder/which.html) is generic, so you can also do:

```dart
expect(
  $(Text).which<Text>(
    (widget) => widget.style?.color == APpColors.error,
  ),
  findsOneWidget,
```

(why are you using `expectLater()` instead of `expect()`? Both functions are synchronous)

But it's actually longer by 2 characters :P (the `<` and `>`). So the answer to your question is "no".

But this got me thinking about how we could improve `PatrolFinder.which()` to be shorter. Maybe `PatrolFinder` could be generic: `PatrolFinder<T>`. 

So that'd let you do:

```dart
expect(
  $(Text).which((widget) => widget.style?.color == APpColors.error),
  findsOneWidget,
```

and type passed to the closure in `which()` would be inferred. I'd have to research this.

**Comment by mleybacreatethrive** [comment]
> Hi @matiasleyba :) Thanks for the kind words.
> 
> [PatrolFinder.which() method](https://pub.dev/documentation/patrol/latest/patrol/PatrolFinder/which.html) is generic, so you can also do:
> 
> ```dart
> expect(
>   $(Text).which<Text>(
>     (widget) => widget.style?.color == AppColors.error,
>   ),
>   findsOneWidget,
> ```
> 
> (BTW, why are you using `expectLater()` instead of `expect()`? Both functions are synchronous)
> 
> But it's actually longer by 2 characters :P (the `<` and `>`). So the answer to your question is "no".
> 
> But this got me thinking about how we could improve `PatrolFinder.which()` to be shorter. Maybe `PatrolFinder` could be generic: `PatrolFinder<T>`.
> 
> So that'd let you do:
> 
> ```dart
> expect(
>   $(Text).which((widget) => widget.style?.color == AppColors.error),
>   findsOneWidget,
> ```
> 
> and type passed to the closure in `which()` would be inferred. I'd have to research this.

Thanks for the reply!

Inferred type on `which()` would be good I think.

**Comment by matiasleyba** [comment]
@bartekpacia Thanks for the reply!

Inferred type where it would be good I think.
