### ISSUE TITLE
Extract finders to a Flutter-only `patrol_finders` package

### ISSUE THREAD

**Issue by josh-burton** [leancodepl/patrol#999]
**Describe the bug**

I've started using Patrol in my widget tests because of the nice syntax with finders etc. It's great!

But when I run my app on iOS, I'm getting issues such as:

`Specs satisfying the `patrol (from `.symlinks/plugins/patrol/ios`)` dependency were found, but they required a higher minimum deployment target.`

I don't want to bump my deployment target, and I don't actually need the Patrol pod as I'm not using it for instrumentation tests.

Is there a supported way to only use Patrol in widget tests and not compile the Patrol plugins in the app?

**Comment by josh-burton** [comment]
I guess ideally the patrol package would be split into patrol and patrol-integration, with the latter containing the native android/ios integration pieces.

**Comment by bartekpacia** [comment]
This can be not as straightforward as it looks like, because `PatrolTester` has a reference to `NativeAutomator`, and `NativeAutomator` holds a reference to `PatrolTester`. See [lib/common.dart](https://github.com/leancodepl/patrol/blob/master/packages/patrol/lib/src/common.dart) in `package:patrol` to see how they're wired together.

**Comment by bartekpacia** [comment]
The solution I have in mind is to add a `Map<String, dynamic>` props to both `PatrolTester` and `NativeAutomator`, and place each other in that map.

**Comment by bartekpacia** [comment]
Once we get this done, we could hook up `patrol_finder`'s tests to [flutter/tests](https://github.com/flutter/tests).

**Comment by jBorkowska** [comment]
size: S
